http:
  routers:
    server:
      rule: 'Host(`unraid.{{ env "DOMAIN" }}`)'
      entryPoints:
        - "web"
      service: 'server@file'
      middlewares:
        - 'rate-limit@file'
        - 'security-headers@file'
        - 'authelia@file'

    nas:
      rule: 'Host(`nas.{{ env "DOMAIN" }}`)'
      entryPoints:
        - "web"
      service: 'nas@file'
      middlewares:
        - 'rate-limit@file'
        - 'security-headers@file'
        - 'authelia@file'

  services:
    server:
      loadBalancer:
        servers:
          - url: 'http://{{ env "UNRAID_IP" }}:3480'

    nas:
      loadBalancer:
        servers:
          - url: 'http://{{ env "NAS_IP" }}:5080'
