http:
  routers:
    grafana:
      rule: 'Host(`grafana.{{ env "DOMAIN" }}`)'
      entryPoints:
        - 'web'
      service: 'grafana@file'
      middlewares:
        - 'rate-limit@file'
        - 'security-headers@file'
        - 'authelia@file'

  services:
    grafana:
      loadBalancer:
        servers:
          - url: 'http://grafana:3000/'
        healthCheck:
          path: '/api/health'
          interval: '30s'
